if(PUMPKIN_SANITIZE)
  if(PUMPKIN_SANITIZE MATCHES "thread" AND PUMPKIN_SANITIZE MATCHES "address")
    message(FATAL_ERROR "ThreadSanitizer cannot be combined with AddressSanitizer")
  endif()
  message(STATUS "Pumpkin: sanitizers enabled: ${PUMPKIN_SANITIZE}")
  add_compile_options(-fsanitize=${PUMPKIN_SANITIZE} -fno-omit-frame-pointer -fno-sanitize-recover=all)
  add_link_options(-fsanitize=${PUMPKIN_SANITIZE})
endif()